packages:
  - 'shared'
  - 'shell'
  - 'mfe-auth'
  - 'mfe-accounts'
  - 'mfe-transfer'
  - 'mfe-cards'
  - 'mfe-loans'
  - 'mfe-profile'
  # @plop:workspace (generator chèn MFE mới bên trên dòng này)
